(ns cljs-react-material-ui.rum
  (:refer-clojure :exclude [list stepper])
  (:require-macros [cljs-react-material-ui.core-macros])
  (:require
    [rum.core]
    [cljs-react-material-ui.core-macros]
    ["@material-ui/core" :as MaterialUI]
))

(def selectable-list (clj-react-material-ui.core/adapt-rum-class ((aget MaterialUI "makeSelectable") (aget MaterialUI "List"))))

(def app-bar (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "AppBar")))
(def auto-complete (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "AutoComplete")))
(def avatar (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Avatar")))
(def badge (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Badge")))
(def button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Button")))
(def bottom-navigation (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "BottomNavigation")))
(def bottom-navigation-item (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "BottomNavigationItem")))
(def card (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Card")))
(def card-actions (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardActions")))
(def card-header (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardHeader")))
(def card-media (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardMedia")))
(def card-title (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardTitle")))
(def card-text (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardText")))
(def checkbox (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Checkbox")))
(def chip (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Chip")))
(def circular-progress (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "CircularProgress")))
(def date-picker (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "DatePicker")))
(def dialog (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Dialog")))
(def divider (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Divider")))
(def drawer (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Drawer")))
(def drop-down-menu (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "DropDownMenu")))
(def form-control (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "FormControl")))
(def flat-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "FlatButton")))
(def hidden (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Hidden")))
(def form-helper-text (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "FormHelperText")))
(def floating-action-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "FloatingActionButton")))
(def font-icon (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "FontIcon")))
(def grid (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Grid")))
(def grid-list (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "GridList")))
(def grid-tile (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "GridTile")))
(def icon-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "IconButton")))
(def icon-menu (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "IconMenu")))
(def input-label (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "InputLabel")))
(def linear-progress (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "LinearProgress")))
(def list (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "List")))
(def list-item (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "ListItem")))
(def menu (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Menu")))
(def menu-item (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "MenuItem")))
(def mui-theme-provider (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "MuiThemeProvider")))
(def paper (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Paper")))
(def popover (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Popover")))
(def radio-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "RadioButton")))
(def radio-button-group (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "RadioButtonGroup")))
(def raised-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "RaisedButton")))
(def refresh-indicator (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "RefreshIndicator")))
(def select-field (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "SelectField")))
(def select (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Select")))
(def slider (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Slider")))
(def subheader (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Subheader")))
(def svg-icon (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "SvgIcon")))
(def step (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Step")))
(def step-button (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepButton")))
(def step-content (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepContent")))
(def step-label (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepLabel")))
(def stepper (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Stepper")))
(def snackbar (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Snackbar")))
(def tabs (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Tabs")))
(def tab (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Tab")))
(def table (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Table")))
(def table-body (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableBody")))
(def table-footer (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableFooter")))
(def table-header (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableHeader")))
(def table-header-column (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableHeaderColumn")))
(def table-row (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableRow")))
(def table-row-column (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableRowColumn")))
(def text-field (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TextField")))
(def time-picker (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "TimePicker")))
(def toggle (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Toggle")))
(def toolbar (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "Toolbar")))
(def toolbar-group (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarGroup")))
(def toolbar-separator (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarSeparator")))
(def toolbar-title (clj-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarTitle")))