(ns cljs-react-material-ui.rum
  (:refer-clojure :exclude [list stepper])
  (:require-macros [cljs-react-material-ui.core])
  (:require [rum.core]
            [cljs-react-material-ui.core]
            ["@material-ui/core" :as MaterialUI]
            ))

(def selectable-list (cljs-react-material-ui.core/adapt-rum-class ((aget MaterialUI "makeSelectable") (aget MaterialUI "List"))))

(def app-bar (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "AppBar")))
(def auto-complete (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "AutoComplete")))
(def avatar (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Avatar")))
(def badge (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Badge")))
(def button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Button")))
(def bottom-navigation (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "BottomNavigation")))
(def bottom-navigation-item (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "BottomNavigationItem")))
(def card (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Card")))
(def card-actions (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardActions")))
(def card-header (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardHeader")))
(def card-media (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardMedia")))
(def card-title (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardTitle")))
(def card-text (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CardText")))
(def checkbox (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Checkbox")))
(def chip (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Chip")))
(def circular-progress (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "CircularProgress")))
(def date-picker (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "DatePicker")))
(def dialog (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Dialog")))
(def divider (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Divider")))
(def drawer (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Drawer")))
(def drop-down-menu (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "DropDownMenu")))
(def form-control (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "FormControl")))
(def flat-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "FlatButton")))
(def hidden (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Hidden")))
(def form-helper-text (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "FormHelperText")))
(def floating-action-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "FloatingActionButton")))
(def font-icon (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "FontIcon")))
(def grid (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Grid")))
(def grid-list (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "GridList")))
(def grid-tile (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "GridTile")))
(def icon-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "IconButton")))
(def icon-menu (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "IconMenu")))
(def input-label (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "InputLabel")))
(def linear-progress (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "LinearProgress")))
(def list (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "List")))
(def list-item (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "ListItem")))
(def menu (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Menu")))
(def menu-item (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "MenuItem")))
(def mui-theme-provider (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "MuiThemeProvider")))
(def paper (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Paper")))
(def popover (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Popover")))
(def radio-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "RadioButton")))
(def radio-button-group (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "RadioButtonGroup")))
(def raised-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "RaisedButton")))
(def refresh-indicator (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "RefreshIndicator")))
(def select-field (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "SelectField")))
(def select (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Select")))
(def slider (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Slider")))
(def subheader (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Subheader")))
(def svg-icon (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "SvgIcon")))
(def step (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Step")))
(def step-button (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepButton")))
(def step-content (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepContent")))
(def step-label (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "StepLabel")))
(def stepper (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Stepper")))
(def snackbar (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Snackbar")))
(def tabs (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Tabs")))
(def tab (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Tab")))
(def table (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Table")))
(def table-body (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableBody")))
(def table-footer (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableFooter")))
(def table-header (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableHeader")))
(def table-header-column (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableHeaderColumn")))
(def table-row (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableRow")))
(def table-row-column (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TableRowColumn")))
(def text-field (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TextField")))
(def time-picker (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "TimePicker")))
(def toggle (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Toggle")))
(def toolbar (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "Toolbar")))
(def toolbar-group (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarGroup")))
(def toolbar-separator (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarSeparator")))
(def toolbar-title (cljs-react-material-ui.core/adapt-rum-class (aget MaterialUI "ToolbarTitle")))